     
version: '3.4'

networks:
    myAppNetwork:        

services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=myStong_Password123# 
    mediklaud:
        container_name: mediklaudapi
        image: ${DOCKER_REGISTRY-}mediklaud:latest
        ports:
            - 8001:80 
        build:
          context: .
          dockerfile: mediklaud/Dockerfile
        depends_on:
            - SqlServerDb
